
package com.psr.record.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Wed Jan 30 21:52:49 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "AddFactsResponse", namespace = "http://record.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddFactsResponse", namespace = "http://record.psr.com/")

public class AddFactsResponse {


}

