
package com.psr.user.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Mon Jan 28 22:46:54 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "AddUserResponse", namespace = "http://user.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddUserResponse", namespace = "http://user.psr.com/")

public class AddUserResponse {


}

