
package com.psr.user.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Thu Jan 31 15:49:17 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "DeleteUserResponse", namespace = "http://user.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeleteUserResponse", namespace = "http://user.psr.com/")

public class DeleteUserResponse {


}

