
package com.psr.user.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Mon Jan 28 22:47:33 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "GetAllUsersResponse", namespace = "http://user.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAllUsersResponse", namespace = "http://user.psr.com/")

public class GetAllUsersResponse {

    @XmlElement(name = "return")
    private java.util.ArrayList<com.psr.model.User> _return;

    public java.util.ArrayList<com.psr.model.User> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.ArrayList<com.psr.model.User> new_return)  {
        this._return = new_return;
    }

}

