
package com.psr.user.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Wed Jan 30 22:18:32 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "GetUserUUID", namespace = "http://user.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUserUUID", namespace = "http://user.psr.com/")

public class GetUserUUID {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

