--------------------------------------------------------
--  文件已创建 - 星期四-四月-25-2013   
--------------------------------------------------------
  DROP TABLE "PSR"."AUTH_专题" cascade constraints;
  DROP TABLE "PSR"."AUTH_事实" cascade constraints;
  DROP TABLE "PSR"."AUTH_添加记录" cascade constraints;
  DROP TABLE "PSR"."AUTH_用户授权" cascade constraints;
  DROP TABLE "PSR"."AUTH_电厂" cascade constraints;
  DROP TABLE "PSR"."AUTH_结论" cascade constraints;
  DROP TABLE "PSR"."AUTH_要素" cascade constraints;
  DROP TABLE "PSR"."PSR_FACT" cascade constraints;
  DROP TABLE "PSR"."PSR_FILE" cascade constraints;
  DROP TABLE "PSR"."PSR_RECORD" cascade constraints;
  DROP TABLE "PSR"."PSR_RECORDRESULT" cascade constraints;
  DROP TABLE "PSR"."SYS_PERMISSION" cascade constraints;
  DROP TABLE "PSR"."SYS_ROLE" cascade constraints;
  DROP TABLE "PSR"."SYS_ROLEPERMISSION_REL" cascade constraints;
  DROP TABLE "PSR"."SYS_USER" cascade constraints;
  DROP TABLE "PSR"."SYS_USERPERMISSION_REL" cascade constraints;
  DROP TABLE "PSR"."SYS_USERROLE_REL" cascade constraints;
  DROP TABLE "PSR"."TLK_专题" cascade constraints;
  DROP TABLE "PSR"."TLK_事实" cascade constraints;
  DROP TABLE "PSR"."TLK_添加记录" cascade constraints;
  DROP TABLE "PSR"."TLK_用户授权" cascade constraints;
  DROP TABLE "PSR"."TLK_电厂" cascade constraints;
  DROP TABLE "PSR"."TLK_结论" cascade constraints;
  DROP TABLE "PSR"."TLK_要素" cascade constraints;
  DROP TABLE "PSR"."T_ACTORHIS" cascade constraints;
  DROP TABLE "PSR"."T_ACTORRT" cascade constraints;
  DROP TABLE "PSR"."T_CIRCULATOR" cascade constraints;
  DROP TABLE "PSR"."T_COUNTER" cascade constraints;
  DROP TABLE "PSR"."T_DOCUMENT" cascade constraints;
  DROP TABLE "PSR"."T_FLOWSTATERT" cascade constraints;
  DROP TABLE "PSR"."T_FLOW_INTERVENTION" cascade constraints;
  DROP TABLE "PSR"."T_FLOW_PROXY" cascade constraints;
  DROP TABLE "PSR"."T_NODERT" cascade constraints;
  DROP TABLE "PSR"."T_PENDING" cascade constraints;
  DROP TABLE "PSR"."T_PENDING_ACTOR_SET" cascade constraints;
  DROP TABLE "PSR"."T_RELATIONHIS" cascade constraints;
  DROP TABLE "PSR"."T_UPLOAD" cascade constraints;
  DROP TABLE "PSR"."ZJ_ORGANIZATION" cascade constraints;
  DROP TABLE "PSR"."ZJ_RECORD_PER" cascade constraints;
  DROP TABLE "PSR"."ZJ_ROLE_ORG_REL" cascade constraints;
  DROP TABLE "PSR"."ZJ_SYSTEM_INFO" cascade constraints;
  DROP TABLE "PSR"."ZJ_SYSTEM_RECORD_REL" cascade constraints;
  DROP TABLE "PSR"."ZJ_USER_SYSTEM_DATAP_REL" cascade constraints;
  DROP PACKAGE "PSR"."PERMISSIONPKG";
  DROP PACKAGE "PSR"."USERPKG";
  DROP PROCEDURE "PSR"."ADDFACT";
  DROP PROCEDURE "PSR"."ADDFILE";
  DROP PROCEDURE "PSR"."ADDPERMISSION";
  DROP PROCEDURE "PSR"."ADDRECORD";
  DROP PROCEDURE "PSR"."ADDRESULT";
  DROP PROCEDURE "PSR"."ADDUSER";
  DROP PROCEDURE "PSR"."ADDUSERPERMISSIONREL";
  DROP PROCEDURE "PSR"."SHOWALLPERMISSION";
  DROP PROCEDURE "PSR"."SHOWALLUSER";
  DROP PROCEDURE "PSR"."TEST";
--------------------------------------------------------
--  DDL for Table AUTH_专题
--------------------------------------------------------

  CREATE TABLE "PSR"."AUTH_专题" 
   (	"ID" VARCHAR2(200 BYTE), 
	"DOC_ID" VARCHAR2(200 BYTE), 
	"VALUE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_事实
--------------------------------------------------------

  CREATE TABLE "PSR"."AUTH_事实" 
   (	"ID" VARCHAR2(200 BYTE), 
	"DOC_ID" VARCHAR2(200 BYTE), 
	"VALUE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_添加记录
--------------------------------------------------------

  CREATE TABLE "PSR"."AUTH_添加记录" 
   (	"ID" VARCHAR2(1000 BYTE), 
	"DOC_ID" VARCHAR2(1000 BYTE), 
	"VALUE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_用户授权
--------------------------------------------------------

  CREATE TABLE "PSR"."AUTH_用户授权" 
   (	"ID" VARCHAR2(200 BYTE), 
	"DOC_ID" VARCHAR2(200 BYTE), 
	"VALUE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_电厂
--------------------------------------------------------

  CREATE TABLE "PSR"."AUTH_电厂" 
   (	"ID" VARCHAR2(200 BYTE), 
	"DOC_ID" VARCHAR2(200 BYTE), 
	"VALUE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_结论
--------------------------------------------------------

  CREATE TABLE "PSR"."AUTH_结论" 
   (	"ID" VARCHAR2(200 BYTE), 
	"DOC_ID" VARCHAR2(200 BYTE), 
	"VALUE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AUTH_要素
--------------------------------------------------------

  CREATE TABLE "PSR"."AUTH_要素" 
   (	"ID" VARCHAR2(200 BYTE), 
	"DOC_ID" VARCHAR2(200 BYTE), 
	"VALUE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PSR_FACT
--------------------------------------------------------

  CREATE TABLE "PSR"."PSR_FACT" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"AGAINSTFACTS" VARCHAR2(255 BYTE), 
	"ASSOCIATERESULT" NUMBER(10,0), 
	"CONTENT" CLOB, 
	"FACTNO" NUMBER(10,0), 
	"FUHEXIANG" VARCHAR2(255 BYTE), 
	"IMAGES_PATH" VARCHAR2(255 BYTE), 
	"ISFH" NUMBER(1,0), 
	"ISPC" NUMBER(1,0), 
	"PIANCHAXIANG" VARCHAR2(255 BYTE), 
	"RECORDID" VARCHAR2(255 BYTE), 
	"RECORDNO" VARCHAR2(255 BYTE), 
	"STRFACTAPPROVECOMMENT" VARCHAR2(255 BYTE), 
	"STRFACTSTATUS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PSR_FILE
--------------------------------------------------------

  CREATE TABLE "PSR"."PSR_FILE" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"FILE_DESC" VARCHAR2(255 BYTE), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"FILE_PATH" VARCHAR2(255 BYTE), 
	"RE_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PSR_RECORD
--------------------------------------------------------

  CREATE TABLE "PSR"."PSR_RECORD" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"APPROVERBY" VARCHAR2(255 BYTE), 
	"APPROVERTIME" DATE, 
	"COMMENTS" CLOB, 
	"COUNT" VARCHAR2(255 BYTE), 
	"DANWEI" VARCHAR2(255 BYTE), 
	"EQUIPTMENT" VARCHAR2(255 BYTE), 
	"FACILITY" VARCHAR2(255 BYTE), 
	"HAVEATTACHED" NUMBER(1,0), 
	"HAVEQIANGXIANG" NUMBER(1,0), 
	"HAVERUOXIANG" NUMBER(1,0), 
	"ISUPDATED" NUMBER(1,0), 
	"ISUPLOAD" NUMBER(1,0), 
	"INPUTTIME" DATE, 
	"INPUTUSER" VARCHAR2(255 BYTE), 
	"INPUTUSERSUOXIE" VARCHAR2(255 BYTE), 
	"ISACTIVITYINSPECTION" NUMBER(1,0), 
	"ISCOMMUNICATION" NUMBER(1,0), 
	"ISCOMPLIANCE" NUMBER(1,0), 
	"ISDOCUMENTREVISION" NUMBER(1,0), 
	"ISWALKDOWN" NUMBER(1,0), 
	"RESULT" VARCHAR2(255 BYTE), 
	"RECORDDESCIPTION" VARCHAR2(4000 BYTE), 
	"RECORDNO" VARCHAR2(255 BYTE), 
	"SENDBACKREASON" VARCHAR2(4000 BYTE), 
	"PSR_STATUS" VARCHAR2(255 BYTE), 
	"TOPIC" VARCHAR2(3000 BYTE), 
	"TOPICDESC" VARCHAR2(4000 BYTE), 
	"UPLOADEDTIME" DATE, 
	"UPDATEDTIME" DATE, 
	"YAOSUBINHAO" VARCHAR2(255 BYTE), 
	"ZHUANGTIBIANHAO" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("COMMENTS") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PSR_RECORDRESULT
--------------------------------------------------------

  CREATE TABLE "PSR"."PSR_RECORDRESULT" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"CONTENT" CLOB, 
	"FACTNOS" VARCHAR2(255 BYTE), 
	"ISFH" NUMBER(1,0), 
	"ISPC" NUMBER(1,0), 
	"RECORDID" VARCHAR2(255 BYTE), 
	"RECORDNO" VARCHAR2(255 BYTE), 
	"RESULTNO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SYS_PERMISSION
--------------------------------------------------------

  CREATE TABLE "PSR"."SYS_PERMISSION" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"PER_DESC" VARCHAR2(255 BYTE), 
	"PER_ICON" VARCHAR2(255 BYTE), 
	"PER_NAME" VARCHAR2(255 BYTE), 
	"PER_PID" VARCHAR2(255 BYTE), 
	"PER_SORTNO" NUMBER(10,0), 
	"PER_TYPE" NUMBER(10,0), 
	"URL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SYS_ROLE
--------------------------------------------------------

  CREATE TABLE "PSR"."SYS_ROLE" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"ORG_ID" VARCHAR2(255 BYTE), 
	"ROLE_DESC" VARCHAR2(255 BYTE), 
	"ROLE_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SYS_ROLEPERMISSION_REL
--------------------------------------------------------

  CREATE TABLE "PSR"."SYS_ROLEPERMISSION_REL" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"PERM_ID" VARCHAR2(255 BYTE), 
	"ROLE_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SYS_USER
--------------------------------------------------------

  CREATE TABLE "PSR"."SYS_USER" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"LOGIN_NAME" VARCHAR2(255 BYTE), 
	"LOGIN_PASSWORD" VARCHAR2(255 BYTE), 
	"ROLE_ID" VARCHAR2(255 BYTE), 
	"UNIT_ID" VARCHAR2(255 BYTE), 
	"USER_ADDRESS" VARCHAR2(255 BYTE), 
	"USER_AGE" NUMBER(10,0), 
	"USER_DESC" VARCHAR2(255 BYTE), 
	"USER_NAME" VARCHAR2(255 BYTE), 
	"USER_SEX" NUMBER(5,0), 
	"USER_TEL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SYS_USERPERMISSION_REL
--------------------------------------------------------

  CREATE TABLE "PSR"."SYS_USERPERMISSION_REL" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"PERM_ID" VARCHAR2(255 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SYS_USERROLE_REL
--------------------------------------------------------

  CREATE TABLE "PSR"."SYS_USERROLE_REL" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"ROLE_ID" VARCHAR2(255 BYTE), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TLK_专题
--------------------------------------------------------

  CREATE TABLE "PSR"."TLK_专题" 
   (	"PARENT" VARCHAR2(200 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"FORMNAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"AUDITUSER" VARCHAR2(200 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(200 BYTE), 
	"AUTHOR_DEPT_INDEX" VARCHAR2(200 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"ISSUBDOC" NUMBER(10,0), 
	"FORMID" VARCHAR2(200 BYTE), 
	"ISTMP" NUMBER(10,0), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"VERSIONS" NUMBER(10,0), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"STATEINT" NUMBER(10,0), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"AUDITORNAMES" CLOB, 
	"LASTFLOWOPERATION" VARCHAR2(200 BYTE), 
	"LASTMODIFIER" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"AUDITORLIST" CLOB, 
	"ID" VARCHAR2(200 BYTE), 
	"ITEM_专题编号" VARCHAR2(200 BYTE), 
	"ITEM_属于要素" VARCHAR2(200 BYTE), 
	"ITEM_专题名" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("AUDITORNAMES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORLIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TLK_事实
--------------------------------------------------------

  CREATE TABLE "PSR"."TLK_事实" 
   (	"PARENT" VARCHAR2(200 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"FORMNAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"AUDITUSER" VARCHAR2(200 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(200 BYTE), 
	"AUTHOR_DEPT_INDEX" VARCHAR2(200 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"ISSUBDOC" NUMBER(10,0), 
	"FORMID" VARCHAR2(200 BYTE), 
	"ISTMP" NUMBER(10,0), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"VERSIONS" NUMBER(10,0), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"STATEINT" NUMBER(10,0), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"AUDITORNAMES" CLOB, 
	"LASTFLOWOPERATION" VARCHAR2(200 BYTE), 
	"LASTMODIFIER" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"AUDITORLIST" CLOB, 
	"ID" VARCHAR2(200 BYTE), 
	"ITEM_图片上传" CLOB, 
	"ITEM_事实内容" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("AUDITORNAMES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORLIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ITEM_图片上传") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ITEM_事实内容") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TLK_添加记录
--------------------------------------------------------

  CREATE TABLE "PSR"."TLK_添加记录" 
   (	"PARENT" VARCHAR2(1000 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"FORMNAME" VARCHAR2(1000 BYTE), 
	"OWNER" VARCHAR2(1000 BYTE), 
	"STATE" VARCHAR2(1000 BYTE), 
	"AUDITUSER" VARCHAR2(1000 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(1000 BYTE), 
	"AUTHOR_DEPT_INDEX" VARCHAR2(1000 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"ISSUBDOC" NUMBER(1,0), 
	"FORMID" VARCHAR2(1000 BYTE), 
	"ISTMP" NUMBER(1,0), 
	"FLOWID" VARCHAR2(1000 BYTE), 
	"VERSIONS" NUMBER(10,0), 
	"SORTID" VARCHAR2(1000 BYTE), 
	"APPLICATIONID" VARCHAR2(1000 BYTE), 
	"STATEINT" NUMBER(10,0), 
	"STATELABEL" VARCHAR2(1000 BYTE), 
	"AUDITORNAMES" CLOB, 
	"LASTFLOWOPERATION" VARCHAR2(1000 BYTE), 
	"LASTMODIFIER" VARCHAR2(1000 BYTE), 
	"DOMAINID" VARCHAR2(1000 BYTE), 
	"AUDITORLIST" CLOB, 
	"ITEM_电厂" VARCHAR2(1000 BYTE), 
	"ITEM_要素" VARCHAR2(1000 BYTE), 
	"ITEM_保存时间" VARCHAR2(1000 BYTE), 
	"ITEM_专题" VARCHAR2(1000 BYTE), 
	"ITEM_提交时间" VARCHAR2(1000 BYTE), 
	"ITEM_记录编号" VARCHAR2(1000 BYTE), 
	"ITEM_录入员" VARCHAR2(1000 BYTE), 
	"ITEM_状态" VARCHAR2(1000 BYTE), 
	"ITEM_审查对象" VARCHAR2(1000 BYTE), 
	"ITEM_设备编码" VARCHAR2(1000 BYTE), 
	"ITEM_审查范围" CLOB, 
	"ITEM_用户" VARCHAR2(1000 BYTE), 
	"ITEM_审查方式" CLOB, 
	"ITEM_事实描述" VARCHAR2(1000 BYTE), 
	"ID" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("AUDITORNAMES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORLIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ITEM_审查范围") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ITEM_审查方式") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TLK_用户授权
--------------------------------------------------------

  CREATE TABLE "PSR"."TLK_用户授权" 
   (	"PARENT" VARCHAR2(200 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"FORMNAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"AUDITUSER" VARCHAR2(200 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(200 BYTE), 
	"AUTHOR_DEPT_INDEX" VARCHAR2(200 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"ISSUBDOC" NUMBER(10,0), 
	"FORMID" VARCHAR2(200 BYTE), 
	"ISTMP" NUMBER(10,0), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"VERSIONS" NUMBER(10,0), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"STATEINT" NUMBER(10,0), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"LASTFLOWOPERATION" VARCHAR2(200 BYTE), 
	"LASTMODIFIER" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"ID" VARCHAR2(200 BYTE), 
	"ITEM_电厂" VARCHAR2(200 BYTE), 
	"ITEM_用户" VARCHAR2(200 BYTE), 
	"ITEM_要素" VARCHAR2(200 BYTE), 
	"ITEM_专题" VARCHAR2(200 BYTE), 
	"AUDITORLIST" VARCHAR2(200 BYTE), 
	"AUDITORNAMES" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TLK_电厂
--------------------------------------------------------

  CREATE TABLE "PSR"."TLK_电厂" 
   (	"PARENT" VARCHAR2(200 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"FORMNAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"AUDITUSER" VARCHAR2(200 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(200 BYTE), 
	"AUTHOR_DEPT_INDEX" VARCHAR2(200 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"ISSUBDOC" NUMBER(10,0), 
	"FORMID" VARCHAR2(200 BYTE), 
	"ISTMP" NUMBER(10,0), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"VERSIONS" NUMBER(10,0), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"STATEINT" NUMBER(10,0), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"AUDITORNAMES" CLOB, 
	"LASTFLOWOPERATION" VARCHAR2(200 BYTE), 
	"LASTMODIFIER" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"AUDITORLIST" CLOB, 
	"ID" VARCHAR2(200 BYTE), 
	"ITEM_电厂编号" VARCHAR2(200 BYTE), 
	"ITEM_电厂名称" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("AUDITORNAMES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORLIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TLK_结论
--------------------------------------------------------

  CREATE TABLE "PSR"."TLK_结论" 
   (	"PARENT" VARCHAR2(200 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"FORMNAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"AUDITUSER" VARCHAR2(200 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(200 BYTE), 
	"AUTHOR_DEPT_INDEX" VARCHAR2(200 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"ISSUBDOC" NUMBER(10,0), 
	"FORMID" VARCHAR2(200 BYTE), 
	"ISTMP" NUMBER(10,0), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"VERSIONS" NUMBER(10,0), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"STATEINT" NUMBER(10,0), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"AUDITORNAMES" CLOB, 
	"LASTFLOWOPERATION" VARCHAR2(200 BYTE), 
	"LASTMODIFIER" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"AUDITORLIST" CLOB, 
	"ITEM_针对事实编号" VARCHAR2(200 BYTE), 
	"ITEM_结论内容" CLOB, 
	"ITEM_符合项" VARCHAR2(200 BYTE), 
	"ID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("AUDITORNAMES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORLIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ITEM_结论内容") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TLK_要素
--------------------------------------------------------

  CREATE TABLE "PSR"."TLK_要素" 
   (	"PARENT" VARCHAR2(200 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"FORMNAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"AUDITUSER" VARCHAR2(200 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(200 BYTE), 
	"AUTHOR_DEPT_INDEX" VARCHAR2(200 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"ISSUBDOC" NUMBER(10,0), 
	"FORMID" VARCHAR2(200 BYTE), 
	"ISTMP" NUMBER(10,0), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"VERSIONS" NUMBER(10,0), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"STATEINT" NUMBER(10,0), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"AUDITORNAMES" CLOB, 
	"LASTFLOWOPERATION" VARCHAR2(200 BYTE), 
	"LASTMODIFIER" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"AUDITORLIST" CLOB, 
	"ID" VARCHAR2(200 BYTE), 
	"ITEM_要素编号" VARCHAR2(200 BYTE), 
	"ITEM_要素名称" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("AUDITORNAMES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORLIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_ACTORHIS
--------------------------------------------------------

  CREATE TABLE "PSR"."T_ACTORHIS" 
   (	"ID" VARCHAR2(200 BYTE), 
	"ACTORID" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"AGENTID" VARCHAR2(200 BYTE), 
	"AGENTNAME" VARCHAR2(200 BYTE), 
	"TYPE" NUMBER(10,0), 
	"PROCESSTIME" TIMESTAMP (6), 
	"ATTITUDE" VARCHAR2(200 BYTE), 
	"NODEHIS_ID" VARCHAR2(200 BYTE), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"FLOWSTATERT_ID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_ACTORRT
--------------------------------------------------------

  CREATE TABLE "PSR"."T_ACTORRT" 
   (	"ID" VARCHAR2(200 BYTE), 
	"ACTORID" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"ISPROCESSED" NUMBER(10,0), 
	"TYPE" NUMBER(10,0), 
	"NODERT_ID" VARCHAR2(200 BYTE), 
	"FLOWSTATERT_ID" VARCHAR2(200 BYTE), 
	"DEADLINE" TIMESTAMP (6), 
	"SORTID" VARCHAR2(200 BYTE), 
	"PENDING" NUMBER(10,0), 
	"ISREAD" NUMBER(10,0), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_CIRCULATOR
--------------------------------------------------------

  CREATE TABLE "PSR"."T_CIRCULATOR" 
   (	"ID" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"USERID" VARCHAR2(200 BYTE), 
	"DOC_ID" VARCHAR2(200 BYTE), 
	"NODERT_ID" VARCHAR2(200 BYTE), 
	"FLOWSTATERT_ID" VARCHAR2(200 BYTE), 
	"CCTIME" TIMESTAMP (6), 
	"READTIME" TIMESTAMP (6), 
	"DEADLINE" TIMESTAMP (6), 
	"ISREAD" NUMBER(10,0), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"VERSION" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_COUNTER
--------------------------------------------------------

  CREATE TABLE "PSR"."T_COUNTER" 
   (	"ID" VARCHAR2(200 BYTE), 
	"COUNTER" NUMBER(10,0), 
	"NAME" VARCHAR2(200 BYTE), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "PSR"."T_DOCUMENT" 
   (	"ID" VARCHAR2(200 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"FORMNAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(200 BYTE), 
	"AUTHOR_DEPT_INDEX" VARCHAR2(200 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"ISSUBDOC" NUMBER(10,0), 
	"FORMID" VARCHAR2(200 BYTE), 
	"ISTMP" NUMBER(10,0), 
	"VERSIONS" NUMBER(10,0), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"INITIATOR" VARCHAR2(200 BYTE), 
	"AUDITUSER" VARCHAR2(200 BYTE), 
	"AUDITORNAMES" CLOB, 
	"LASTFLOWOPERATION" VARCHAR2(200 BYTE), 
	"PARENT" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"STATEINT" NUMBER(10,0), 
	"LASTMODIFIER" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"AUDITORLIST" CLOB, 
	"MAPPINGID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("AUDITORNAMES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORLIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_FLOWSTATERT
--------------------------------------------------------

  CREATE TABLE "PSR"."T_FLOWSTATERT" 
   (	"ID" VARCHAR2(200 BYTE), 
	"DOCID" VARCHAR2(200 BYTE), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"STATE" NUMBER(10,0), 
	"SORTID" VARCHAR2(200 BYTE), 
	"PARENT" VARCHAR2(200 BYTE), 
	"FLOWNAME" VARCHAR2(200 BYTE), 
	"FLOWXML" CLOB, 
	"LASTMODIFIERID" VARCHAR2(200 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"SUBFLOWNODEID" VARCHAR2(200 BYTE), 
	"COMPLETE" NUMBER(10,0), 
	"CALLBACK" NUMBER(10,0), 
	"TOKEN" VARCHAR2(200 BYTE), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"INITIATOR" VARCHAR2(200 BYTE), 
	"AUDITUSER" VARCHAR2(200 BYTE), 
	"AUDITORNAMES" CLOB, 
	"AUDITORLIST" CLOB, 
	"LASTFLOWOPERATION" VARCHAR2(200 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"SUB_POSITION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FLOWXML") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORNAMES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORLIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_FLOW_INTERVENTION
--------------------------------------------------------

  CREATE TABLE "PSR"."T_FLOW_INTERVENTION" 
   (	"ID" VARCHAR2(200 BYTE), 
	"SUMMARY" CLOB, 
	"FLOWNAME" VARCHAR2(200 BYTE), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"INITIATOR" VARCHAR2(200 BYTE), 
	"LASTAUDITOR" VARCHAR2(200 BYTE), 
	"FIRSTPROCESSTIME" TIMESTAMP (6), 
	"LASTPROCESSTIME" TIMESTAMP (6), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"FORMID" VARCHAR2(200 BYTE), 
	"DOCID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"VERSION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SUMMARY") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_FLOW_PROXY
--------------------------------------------------------

  CREATE TABLE "PSR"."T_FLOW_PROXY" 
   (	"ID" VARCHAR2(200 BYTE), 
	"FLOWNAME" VARCHAR2(200 BYTE), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"AGENTS" CLOB, 
	"AGENTSNAME" CLOB, 
	"OWNER" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"VERSION" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("AGENTS") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("AGENTSNAME") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table T_NODERT
--------------------------------------------------------

  CREATE TABLE "PSR"."T_NODERT" 
   (	"ID" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"NODEID" VARCHAR2(200 BYTE), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"DOCID" VARCHAR2(200 BYTE), 
	"FLOWSTATERT_ID" VARCHAR2(200 BYTE), 
	"SORTID" VARCHAR2(200 BYTE), 
	"NOTIFIABLE" NUMBER(10,0), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"FLOWOPTION" VARCHAR2(200 BYTE), 
	"SPLITTOKEN" VARCHAR2(200 BYTE), 
	"PASSCONDITION" NUMBER(10,0), 
	"PARENTNODERTID" VARCHAR2(200 BYTE), 
	"DEADLINE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_PENDING
--------------------------------------------------------

  CREATE TABLE "PSR"."T_PENDING" 
   (	"ID" VARCHAR2(200 BYTE), 
	"DOCID" VARCHAR2(200 BYTE), 
	"LASTMODIFIED" TIMESTAMP (6), 
	"FORMNAME" VARCHAR2(200 BYTE), 
	"OWNER" VARCHAR2(200 BYTE), 
	"AUDITDATE" TIMESTAMP (6), 
	"AUTHOR" VARCHAR2(200 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"ISSUBDOC" NUMBER(10,0), 
	"CHANNELSNAME" VARCHAR2(200 BYTE), 
	"FORMID" VARCHAR2(200 BYTE), 
	"CHILDS" VARCHAR2(200 BYTE), 
	"ISTMP" NUMBER(10,0), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"VERSIONS" NUMBER(10,0), 
	"SORTID" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"STATELABEL" VARCHAR2(200 BYTE), 
	"AUDITUSER" VARCHAR2(200 BYTE), 
	"AUDITORNAMES" CLOB, 
	"LASTFLOWOPERATION" VARCHAR2(200 BYTE), 
	"STATEINT" NUMBER(10,0), 
	"PARENT" VARCHAR2(200 BYTE), 
	"STATE" VARCHAR2(200 BYTE), 
	"LASTMODIFIER" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE), 
	"AUDITORLIST" CLOB, 
	"SUMMARY" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("AUDITORNAMES") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("AUDITORLIST") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SUMMARY") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table T_PENDING_ACTOR_SET
--------------------------------------------------------

  CREATE TABLE "PSR"."T_PENDING_ACTOR_SET" 
   (	"DOCID" VARCHAR2(200 BYTE), 
	"ACTORID" VARCHAR2(200 BYTE), 
	"DOMAINID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_RELATIONHIS
--------------------------------------------------------

  CREATE TABLE "PSR"."T_RELATIONHIS" 
   (	"ID" VARCHAR2(200 BYTE), 
	"ACTIONTIME" TIMESTAMP (6), 
	"PROCESSTIME" TIMESTAMP (6), 
	"STARTNODENAME" VARCHAR2(200 BYTE), 
	"FLOWID" VARCHAR2(200 BYTE), 
	"FLOWNAME" VARCHAR2(200 BYTE), 
	"DOCID" VARCHAR2(200 BYTE), 
	"ENDNODEID" VARCHAR2(200 BYTE), 
	"ENDNODENAME" VARCHAR2(200 BYTE), 
	"STARTNODEID" VARCHAR2(200 BYTE), 
	"ISPASSED" NUMBER(10,0), 
	"ATTITUDE" VARCHAR2(200 BYTE), 
	"SORTID" VARCHAR2(200 BYTE), 
	"AUDITOR" VARCHAR2(200 BYTE), 
	"APPLICATIONID" VARCHAR2(200 BYTE), 
	"FLOWOPERATION" VARCHAR2(200 BYTE), 
	"REMINDERCOUNT" NUMBER(10,0), 
	"FLOWSTATERT_ID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_UPLOAD
--------------------------------------------------------

  CREATE TABLE "PSR"."T_UPLOAD" 
   (	"ID" VARCHAR2(200 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"IMGBINARY" BLOB, 
	"FIELDID" VARCHAR2(200 BYTE), 
	"TYPE" VARCHAR2(200 BYTE), 
	"FILESIZE" NUMBER(10,0), 
	"USERID" VARCHAR2(200 BYTE), 
	"MODIFYDATE" VARCHAR2(200 BYTE), 
	"PATH" VARCHAR2(4000 BYTE), 
	"FOLDERPATH" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("IMGBINARY") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ZJ_ORGANIZATION
--------------------------------------------------------

  CREATE TABLE "PSR"."ZJ_ORGANIZATION" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"ORG_DESC" VARCHAR2(255 BYTE), 
	"ORG_LEVEL" NUMBER(10,0), 
	"ORG_NAME" VARCHAR2(255 BYTE), 
	"ORG_PID" VARCHAR2(255 BYTE), 
	"SYSTEM_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZJ_RECORD_PER
--------------------------------------------------------

  CREATE TABLE "PSR"."ZJ_RECORD_PER" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"TABLE_NAME" VARCHAR2(255 BYTE), 
	"TABLE_PROPERTY" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZJ_ROLE_ORG_REL
--------------------------------------------------------

  CREATE TABLE "PSR"."ZJ_ROLE_ORG_REL" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"ORG_ID" VARCHAR2(255 BYTE), 
	"ROLE_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZJ_SYSTEM_INFO
--------------------------------------------------------

  CREATE TABLE "PSR"."ZJ_SYSTEM_INFO" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"ORG_ID" VARCHAR2(255 BYTE), 
	"SYSTEM_CODE" VARCHAR2(255 BYTE), 
	"SYSTEM_DESC" VARCHAR2(255 BYTE), 
	"SYSTEM_NAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZJ_SYSTEM_RECORD_REL
--------------------------------------------------------

  CREATE TABLE "PSR"."ZJ_SYSTEM_RECORD_REL" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"RECORD_ID" VARCHAR2(255 BYTE), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZJ_USER_SYSTEM_DATAP_REL
--------------------------------------------------------

  CREATE TABLE "PSR"."ZJ_USER_SYSTEM_DATAP_REL" 
   (	"ID" VARCHAR2(255 BYTE), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(255 BYTE), 
	"ENTITY_STATUS" NUMBER(10,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(255 BYTE), 
	"VERSION" NUMBER(10,0), 
	"DATA_PERMISSION_ID" VARCHAR2(255 BYTE), 
	"SYSTEM_ID" VARCHAR2(255 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ZJ_RECORD_PER
--------------------------------------------------------

  ALTER TABLE "PSR"."ZJ_RECORD_PER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."ZJ_RECORD_PER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_PENDING
--------------------------------------------------------

  ALTER TABLE "PSR"."T_PENDING" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_PENDING" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_CIRCULATOR
--------------------------------------------------------

  ALTER TABLE "PSR"."T_CIRCULATOR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_CIRCULATOR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZJ_ORGANIZATION
--------------------------------------------------------

  ALTER TABLE "PSR"."ZJ_ORGANIZATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."ZJ_ORGANIZATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_添加记录
--------------------------------------------------------

  ALTER TABLE "PSR"."AUTH_添加记录" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZJ_SYSTEM_RECORD_REL
--------------------------------------------------------

  ALTER TABLE "PSR"."ZJ_SYSTEM_RECORD_REL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."ZJ_SYSTEM_RECORD_REL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_COUNTER
--------------------------------------------------------

  ALTER TABLE "PSR"."T_COUNTER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_COUNTER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_ACTORHIS
--------------------------------------------------------

  ALTER TABLE "PSR"."T_ACTORHIS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_ACTORHIS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TLK_用户授权
--------------------------------------------------------

  ALTER TABLE "PSR"."TLK_用户授权" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."TLK_用户授权" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_用户授权
--------------------------------------------------------

  ALTER TABLE "PSR"."AUTH_用户授权" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."AUTH_用户授权" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_结论
--------------------------------------------------------

  ALTER TABLE "PSR"."AUTH_结论" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."AUTH_结论" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PSR_FILE
--------------------------------------------------------

  ALTER TABLE "PSR"."PSR_FILE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."PSR_FILE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_USER
--------------------------------------------------------

  ALTER TABLE "PSR"."SYS_USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."SYS_USER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PSR_RECORD
--------------------------------------------------------

  ALTER TABLE "PSR"."PSR_RECORD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."PSR_RECORD" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZJ_USER_SYSTEM_DATAP_REL
--------------------------------------------------------

  ALTER TABLE "PSR"."ZJ_USER_SYSTEM_DATAP_REL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."ZJ_USER_SYSTEM_DATAP_REL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_专题
--------------------------------------------------------

  ALTER TABLE "PSR"."AUTH_专题" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."AUTH_专题" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TLK_要素
--------------------------------------------------------

  ALTER TABLE "PSR"."TLK_要素" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."TLK_要素" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TLK_结论
--------------------------------------------------------

  ALTER TABLE "PSR"."TLK_结论" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."TLK_结论" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_事实
--------------------------------------------------------

  ALTER TABLE "PSR"."AUTH_事实" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."AUTH_事实" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PSR_RECORDRESULT
--------------------------------------------------------

  ALTER TABLE "PSR"."PSR_RECORDRESULT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."PSR_RECORDRESULT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TLK_添加记录
--------------------------------------------------------

  ALTER TABLE "PSR"."TLK_添加记录" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_PERMISSION
--------------------------------------------------------

  ALTER TABLE "PSR"."SYS_PERMISSION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."SYS_PERMISSION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_ROLEPERMISSION_REL
--------------------------------------------------------

  ALTER TABLE "PSR"."SYS_ROLEPERMISSION_REL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."SYS_ROLEPERMISSION_REL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_电厂
--------------------------------------------------------

  ALTER TABLE "PSR"."AUTH_电厂" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."AUTH_电厂" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_USERPERMISSION_REL
--------------------------------------------------------

  ALTER TABLE "PSR"."SYS_USERPERMISSION_REL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."SYS_USERPERMISSION_REL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_RELATIONHIS
--------------------------------------------------------

  ALTER TABLE "PSR"."T_RELATIONHIS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_RELATIONHIS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ZJ_ROLE_ORG_REL
--------------------------------------------------------

  ALTER TABLE "PSR"."ZJ_ROLE_ORG_REL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."ZJ_ROLE_ORG_REL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TLK_电厂
--------------------------------------------------------

  ALTER TABLE "PSR"."TLK_电厂" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."TLK_电厂" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TLK_专题
--------------------------------------------------------

  ALTER TABLE "PSR"."TLK_专题" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."TLK_专题" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table ZJ_SYSTEM_INFO
--------------------------------------------------------

  ALTER TABLE "PSR"."ZJ_SYSTEM_INFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."ZJ_SYSTEM_INFO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_USERROLE_REL
--------------------------------------------------------

  ALTER TABLE "PSR"."SYS_USERROLE_REL" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."SYS_USERROLE_REL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_FLOW_PROXY
--------------------------------------------------------

  ALTER TABLE "PSR"."T_FLOW_PROXY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_FLOW_PROXY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "PSR"."T_DOCUMENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_DOCUMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_ROLE
--------------------------------------------------------

  ALTER TABLE "PSR"."SYS_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."SYS_ROLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_要素
--------------------------------------------------------

  ALTER TABLE "PSR"."AUTH_要素" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."AUTH_要素" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_FLOWSTATERT
--------------------------------------------------------

  ALTER TABLE "PSR"."T_FLOWSTATERT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_FLOWSTATERT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_ACTORRT
--------------------------------------------------------

  ALTER TABLE "PSR"."T_ACTORRT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_ACTORRT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PSR_FACT
--------------------------------------------------------

  ALTER TABLE "PSR"."PSR_FACT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."PSR_FACT" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table TLK_事实
--------------------------------------------------------

  ALTER TABLE "PSR"."TLK_事实" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."TLK_事实" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_FLOW_INTERVENTION
--------------------------------------------------------

  ALTER TABLE "PSR"."T_FLOW_INTERVENTION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_FLOW_INTERVENTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table T_NODERT
--------------------------------------------------------

  ALTER TABLE "PSR"."T_NODERT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PSR"."T_NODERT" MODIFY ("ID" NOT NULL ENABLE);











































--------------------------------------------------------
--  DDL for Package PERMISSIONPKG
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PSR"."PERMISSIONPKG" as 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
TYPE PermissionCursor IS REF CURSOR;
end permissionpkg;

/

--------------------------------------------------------
--  DDL for Package USERPKG
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "PSR"."USERPKG" as 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
TYPE UserCursor IS REF CURSOR; 
end userpkg;

/

--------------------------------------------------------
--  DDL for Procedure ADDFACT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."ADDFACT" 
(
  p_id in psr_fact.id%type  
, p_create_date in psr_fact.create_date%type  
, p_create_user in psr_fact.create_user%type  
, p_entity_status in psr_fact.entity_status%type  
, p_update_date in psr_fact.update_date%type  
, p_update_user in psr_fact.update_user%type  
, p_version in psr_fact.version%type  
, p_againstfacts in psr_fact.againstfacts%type  
, p_associateresult in psr_fact.associateresult%type  
, p_content in psr_fact.content%type  
, p_fuhexiang in psr_fact.fuhexiang%type  
, p_isfh in psr_fact.isfh%type  
, p_ispc in psr_fact.ispc%type  
, p_pianchaxiang in psr_fact.pianchaxiang%type  
, p_recordid in psr_fact.recordid%type  
, p_strfactapprovecomment in psr_fact.strfactapprovecomment%type  
, p_strfactstatus in psr_fact.strfactstatus%type  
, p_factno in psr_fact.factno%type  
, p_imagePath in psr_fact.images_path%type
, p_recordNo in psr_fact.recordno%type
) as 
v_count integer;

begin
  select count(*) into v_count from psr_fact where recordno = p_recordNo and factno =p_factno;
  if v_count >0 then
  delete from psr_fact where recordno = p_recordNo and factno =p_factno;
  commit;
  end if;
  
  Insert into PSR_FACT (ID,CREATE_DATE,CREATE_USER,ENTITY_STATUS,UPDATE_DATE,UPDATE_USER,VERSION,AGAINSTFACTS,ASSOCIATERESULT,CONTENT,FUHEXIANG,ISFH,ISPC,PIANCHAXIANG,RECORDID,STRFACTAPPROVECOMMENT,STRFACTSTATUS,FACTNO,images_path,recordno) 
  values (p_id,p_create_date,p_create_user,p_entity_status,p_update_date,p_update_user,0,p_againstfacts,p_associateresult,p_content,p_fuhexiang,p_isfh,p_ispc,p_pianchaxiang,p_recordid,p_strfactapprovecomment,p_strfactstatus,p_factno,p_imagepath,p_recordno);
  commit;
end addfact;

/

--------------------------------------------------------
--  DDL for Procedure ADDFILE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."ADDFILE" 
(
  P_ID IN PSR_FILE.ID%TYPE  
, P_CREATE_DATE IN PSR_FILE.CREATE_DATE%TYPE  
, P_CREATE_USER IN PSR_FILE.CREATE_USER%TYPE  
, P_ENTITY_STATUS IN PSR_FILE.ENTITY_STATUS%TYPE  
, P_UPDATE_DATE IN PSR_FILE.UPDATE_DATE%TYPE  
, P_UPDATE_USER IN PSR_FILE.UPDATE_USER%TYPE  
, P_VERSION IN PSR_FILE.VERSION%TYPE  
, P_FILE_DESC IN PSR_FILE.FILE_DESC%TYPE  
, P_FILE_NAME IN PSR_FILE.FILE_NAME%TYPE  
, P_FILE_PATH IN PSR_FILE.FILE_PATH%TYPE  
, P_RE_ID IN PSR_FILE.RE_ID%TYPE  
) AS 
v_count INTEGER;
BEGIN
select count(*) into v_count from psr_file where file_name = p_file_name and file_path=p_file_path;
if v_count>0 then
delete from psr_file where file_name = p_file_name and file_path=p_file_path;
commit;
end if;

Insert into PSR_FILE (ID,CREATE_DATE,CREATE_USER,ENTITY_STATUS,UPDATE_DATE,UPDATE_USER,VERSION,FILE_DESC,FILE_NAME,FILE_PATH,RE_ID) 
values (P_ID,P_CREATE_DATE,P_CREATE_USER,P_ENTITY_STATUS,P_UPDATE_DATE,P_UPDATE_USER,0,P_FILE_DESC,P_FILE_NAME,P_FILE_PATH,P_RE_ID);


END ADDFILE;

/

--------------------------------------------------------
--  DDL for Procedure ADDPERMISSION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."ADDPERMISSION" 
(
  p_id in sys_permission.id%type  
, p_version in sys_permission.version%type  
, p_short_name in sys_permission.per_desc%type  
, p_name in sys_permission.per_name%type  
, p_father_uuid in sys_permission.per_pid%type  
, p_sort_id in sys_permission.per_sortno%type default 1 
, p_type in sys_permission.per_type%type  
, p_url in sys_permission.url%type default 'url' 
) as 
countpermit integer;

begin
--  select count(*) into countpermit from sys_permission where per_type = p_type and per_name = p_name and per_pid = p_father_uuid;
--  if countpermit=0 then
-- delete * from sys_permission;
  insert into sys_permission(sys_permission.id,sys_permission.version,sys_permission.per_desc,sys_permission.per_name,sys_permission.per_pid
  ,sys_permission.per_sortno,sys_permission.per_type,sys_permission.url)
  values(p_id,p_version,p_short_name,p_name,p_father_uuid,p_sort_id,p_type,p_url);
  commit;
--  end if;
--  if countpermit >0 then
--  update sys_permission set sys_permission.id = p_id,sys_permission.per_desc = p_short_name , per_name = p_name,per_type= p_type,per_pid = p_father_uuid  where per_type = p_type and per_name = p_name and per_pid = p_father_uuid;
--  commit;
--  end if;
end addpermission;

/

--------------------------------------------------------
--  DDL for Procedure ADDRECORD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."ADDRECORD" 
(
  v_id in psr_record.id%type  
, v_create_date in psr_record.create_date%type  
, v_create_user in psr_record.create_user%type  
, v_entity_status in psr_record.entity_status%type  
, v_update_date in psr_record.update_date%type  
, v_update_user in psr_record.update_user%type  
, v_version in psr_record.version%type  
, v_approverby in psr_record.approverby%type  
, v_approvertime in psr_record.approvertime%type  
, v_comments in psr_record.comments%type  
, v_count in psr_record.count%type  
, v_danwei in psr_record.danwei%type  
, v_equiptment in psr_record.equiptment%type  
, v_facility in psr_record.facility%type  
, v_haveattached in psr_record.haveattached%type  
, v_haveqiangxiang in psr_record.haveqiangxiang%type  
, v_haveruoxiang in psr_record.haveruoxiang%type  
, v_isupdated in psr_record.isupdated%type  
, v_isupload in psr_record.isupload%type  
, v_inputtime in psr_record.inputtime%type  
, v_inputuser in psr_record.inputuser%type  
, v_inputusersuoxie in psr_record.inputusersuoxie%type  
, v_isactivityinspection in psr_record.isactivityinspection%type  
, v_iscommunication in psr_record.iscommunication%type  
, v_iscompliance in psr_record.iscompliance%type  
, v_isdocumentrevision in psr_record.isdocumentrevision%type  
, v_iswalkdown in psr_record.iswalkdown%type  
, v_result in psr_record.result%type  
, v_recorddesciption in psr_record.recorddesciption%type  
, v_recordno in psr_record.recordno%type  
, v_sendbackreason in psr_record.sendbackreason%type  
, v_psr_status in psr_record.psr_status%type  
, v_topic in psr_record.topic%type  
, v_topicdesc in psr_record.topicdesc%type  
, v_uploadedtime in psr_record.uploadedtime%type  
, v_updatedtime in psr_record.updatedtime%type  
, v_yaosubinhao in psr_record.yaosubinhao%type  
, v_zhuangtibianhao in psr_record.zhuangtibianhao%type  
) as 
--vv_count integer;
--vv_uploadedtime date;
--vv_psrrecord_row psr_record%ROWTYPE;
vv_count integer;
begin
select count(*) into vv_count from psr_record where recordno = v_recordno;

--if vv_count >0 then
--  select * into vv_psrrecord_row  from psr_record where recordno = v_recordno ;
--end if;
  
  if vv_count=0 then--or vv_psrrecord_row.id is null or vv_psrrecord_row.uploadedtime is null then
   Insert into PSR_RECORD (ID,CREATE_DATE,CREATE_USER,ENTITY_STATUS,UPDATE_DATE,UPDATE_USER,VERSION,APPROVERBY,APPROVERTIME,COMMENTS,COUNT,DANWEI,EQUIPTMENT,FACILITY,HAVEATTACHED,HAVEQIANGXIANG,HAVERUOXIANG,ISUPDATED,ISUPLOAD,INPUTTIME,INPUTUSER,INPUTUSERSUOXIE,ISACTIVITYINSPECTION,ISCOMMUNICATION,ISCOMPLIANCE,ISDOCUMENTREVISION,ISWALKDOWN,RESULT,RECORDDESCIPTION,RECORDNO,SENDBACKREASON,PSR_STATUS,TOPIC,TOPICDESC,UPLOADEDTIME,UPDATEDTIME,YAOSUBINHAO,ZHUANGTIBIANHAO) 
   values (v_id,v_create_date,v_create_user,v_entity_status,v_update_date,v_update_user,0,v_approverby,v_approvertime,v_comments,v_count,v_danwei,v_equiptment,v_facility,v_haveattached,v_haveqiangxiang,v_haveruoxiang,v_isupdated,v_isupload,v_inputtime,v_inputuser,v_inputusersuoxie,v_isactivityinspection,v_iscommunication,v_iscompliance,v_isdocumentrevision,v_iswalkdown,v_result,v_recorddesciption,v_recordno,v_sendbackreason,v_psr_status,v_topic,v_topicdesc,v_uploadedtime,v_updatedtime,v_yaosubinhao,v_zhuangtibianhao);
    commit;
    end if;
 if vv_count=1 then--and vv_psrrecord_row.psr_status<>3 and vv_psrrecord_row.psr_status<>4 then
    --dbms_output.put_line('更新!');
    update psr_record set --id=v_id, 
    create_date = v_create_date, create_user = v_create_user, entity_status = v_entity_status,update_date =v_update_date
    ,update_user = v_update_user,version = v_version , approverby = v_approverby , approvertime = v_approvertime, comments = v_comments, count = v_count,danwei = v_danwei,equiptment=v_equiptment,facility=v_facility,haveattached= v_haveattached,haveqiangxiang=v_haveqiangxiang,haveruoxiang=v_haveruoxiang,isupdated = v_isupdated,ISUPLOAD = v_isupload,inputtime = v_inputtime,inputuser= v_inputuser,inputusersuoxie = v_inputusersuoxie
    ,ISACTIVITYINSPECTION = v_isactivityinspection,ISCOMMUNICATION=v_iscommunication,ISCOMPLIANCE = v_iscompliance,ISDOCUMENTREVISION=v_isdocumentrevision,ISWALKDOWN= v_iswalkdown,RESULT = v_result,RECORDDESCIPTION=v_recorddesciption,RECORDNO=v_recordno,SENDBACKREASON=v_sendbackreason,PSR_STATUS=v_psr_status,TOPIC = v_topic,TOPICDESC = v_topicdesc,UPLOADEDTIME = v_uploadedtime,UPDATEDTIME=v_updatedtime,YAOSUBINHAO= v_yaosubinhao,ZHUANGTIBIANHAO = v_zhuangtibianhao
    where psr_record.recordno = v_recordno;
    commit;
  end if;
end addrecord;

/

--------------------------------------------------------
--  DDL for Procedure ADDRESULT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."ADDRESULT" 
(
  p_id in psr_recordresult.id%type  
, p_create_date in psr_recordresult.create_date%type  
, p_create_user in psr_recordresult.create_user%type  
, p_entity_status in psr_recordresult.entity_status%type  
, p_update_date in psr_recordresult.update_date%type  
, p_update_user in psr_recordresult.update_user%type  
, p_version in psr_recordresult.version%type  
, p_content in psr_recordresult.content%type  
, p_isfh in psr_recordresult.isfh%type  
, p_ispc in psr_recordresult.ispc%type  
, p_recordid in psr_recordresult.recordid%type  
, p_factnos in psr_recordresult.factnos%type  
, p_resultno in psr_recordresult.resultno%type  
, p_recordno in psr_recordresult.recordno%type
) as 
v_count integer;
begin
  select count(*) into v_count from psr_recordresult where recordno = p_recordno and resultno = p_resultno;
  if v_count >0 then
  delete from psr_recordresult where recordno = p_recordno and resultno = p_resultno;
  end if;
  
  Insert into PSR_RECORDRESULT (ID,CREATE_DATE,CREATE_USER,ENTITY_STATUS,UPDATE_DATE,UPDATE_USER,VERSION,CONTENT,ISFH,ISPC,RECORDID,FACTNOS,RESULTNO,recordno) 
  values (p_id,p_create_date,p_create_user,p_entity_status,p_update_date,p_update_user,p_version,p_content,p_isfh,p_ispc,p_recordid,p_factnos,p_resultno,p_recordno);
  commit;
  
end addresult;

/

--------------------------------------------------------
--  DDL for Procedure ADDUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."ADDUSER" 
(
  p_id in sys_user.id%type  
, p_version in sys_user.version%type  
, p_loginname in sys_user.login_name%type default 0 
, p_login_password in sys_user.login_password%type  
, p_role_id in sys_user.role_id%type  
, p_unit_id in sys_user.unit_id%type  
, p_user_name in sys_user.user_name%type  
, p_userDes  in sys_user.user_desc%type
) as 
haveone INTEGER;
begin
select count(*) into haveone from sys_user where login_name = p_loginname;

IF haveone>= 1 THEN
update sys_user set login_password = p_login_password, role_id= p_role_id, unit_id = p_unit_id
,user_desc = p_userDes where login_name = p_loginname;
commit;
else
--IF haveone=0 then
insert into sys_user(sys_user.id,sys_user.version,sys_user.login_name,sys_user.login_password,sys_user.role_id,sys_user.unit_id,sys_user.user_name,user_desc)
values (p_id,p_version,p_loginname,p_login_password,p_role_id,p_unit_id,p_user_name,p_userDes);
commit;
end if;

end adduser;

/

--------------------------------------------------------
--  DDL for Procedure ADDUSERPERMISSIONREL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."ADDUSERPERMISSIONREL" 
(
  p_id in sys_userpermission_rel.id%type  
, p_version in sys_userpermission_rel.version%type  
, p_perm_id in sys_userpermission_rel.perm_id%type  
, p_user_id in sys_userpermission_rel.user_id%type  
) as 
v_count integer;
begin
  select count(*) into v_count from sys_userpermission_rel where perm_id = p_perm_id and user_id = p_user_id;
  if v_count = 0 then
  Insert into SYS_USERPERMISSION_REL (ID,VERSION,PERM_ID,USER_ID) 
  values (p_id,p_version,p_perm_id,p_user_id);
  commit;
  end if;
end adduserpermissionrel;

/

--------------------------------------------------------
--  DDL for Procedure SHOWALLPERMISSION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."SHOWALLPERMISSION" 
(
  permissions out permissionpkg.permissioncursor 
) as 
begin
  open permissions for select * from sys_permission; 
end showallpermission;

/

--------------------------------------------------------
--  DDL for Procedure SHOWALLUSER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."SHOWALLUSER" 
(
  users out userpkg.usercursor  
) as 
begin
  open users for  select * from sys_user;
end showalluser;

/

--------------------------------------------------------
--  DDL for Procedure TEST
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "PSR"."TEST" 
(
  param1 out integer  
) as 
begin
  param1 := 1;
end test;

/

