<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GetAllUserService" targetNamespace="http://user.psr.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://user.psr.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://user.psr.com/" schemaLocation="getalluser_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="Exception">
    <wsdl:part name="Exception" element="tns:Exception">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetAllUsersResponse">
    <wsdl:part name="parameters" element="tns:GetAllUsersResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetAllUsers">
    <wsdl:part name="parameters" element="tns:GetAllUsers">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="GetAllUsersSEI">
    <wsdl:operation name="GetAllUsers">
      <wsdl:input name="GetAllUsers" message="tns:GetAllUsers">
    </wsdl:input>
      <wsdl:output name="GetAllUsersResponse" message="tns:GetAllUsersResponse">
    </wsdl:output>
      <wsdl:fault name="Exception" message="tns:Exception">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GetAllUserServiceSoapBinding" type="tns:GetAllUsersSEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetAllUsers">
      <soap:operation soapAction="urn:GetAllUsers" style="document"/>
      <wsdl:input name="GetAllUsers">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetAllUsersResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="Exception">
        <soap:fault name="Exception" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetAllUserService">
    <wsdl:port name="GetAllUserPort" binding="tns:GetAllUserServiceSoapBinding">
      <soap:address location="http://localhost:9090/GetAllUserPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
