
package com.psr.record.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Wed Jan 30 21:51:33 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "AddRecordsResponse", namespace = "http://record.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddRecordsResponse", namespace = "http://record.psr.com/")

public class AddRecordsResponse {


}

