
package com.psr.UploadFiles.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Fri Feb 22 15:43:45 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "InsertFileDB", namespace = "http://UploadFiles.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsertFileDB", namespace = "http://UploadFiles.psr.com/")

public class InsertFileDB {

    @XmlElement(name = "arg0")
    private java.util.ArrayList<com.psr.model.PSRFile> arg0;

    public java.util.ArrayList<com.psr.model.PSRFile> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.ArrayList<com.psr.model.PSRFile> newArg0)  {
        this.arg0 = newArg0;
    }

}

