<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GetAllPermissionService" targetNamespace="http://permission.psr.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://permission.psr.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://permission.psr.com/" schemaLocation="getallpermission_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="SQLException">
    <wsdl:part name="SQLException" element="tns:SQLException">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetAllPermissionsResponse">
    <wsdl:part name="parameters" element="tns:GetAllPermissionsResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="GetAllPermissions">
    <wsdl:part name="parameters" element="tns:GetAllPermissions">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="ClassNotFoundException">
    <wsdl:part name="ClassNotFoundException" element="tns:ClassNotFoundException">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="GetAllPermissionSEI">
    <wsdl:operation name="GetAllPermissions">
      <wsdl:input name="GetAllPermissions" message="tns:GetAllPermissions">
    </wsdl:input>
      <wsdl:output name="GetAllPermissionsResponse" message="tns:GetAllPermissionsResponse">
    </wsdl:output>
      <wsdl:fault name="ClassNotFoundException" message="tns:ClassNotFoundException">
    </wsdl:fault>
      <wsdl:fault name="SQLException" message="tns:SQLException">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="GetAllPermissionServiceSoapBinding" type="tns:GetAllPermissionSEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="GetAllPermissions">
      <soap:operation soapAction="urn:GetAllPermissions" style="document"/>
      <wsdl:input name="GetAllPermissions">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="GetAllPermissionsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ClassNotFoundException">
        <soap:fault name="ClassNotFoundException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="SQLException">
        <soap:fault name="SQLException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GetAllPermissionService">
    <wsdl:port name="GetAllPermissionPort" binding="tns:GetAllPermissionServiceSoapBinding">
      <soap:address location="http://localhost:9090/GetAllPermissionPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
