
package com.psr.userpermissionrel.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Mon Jan 28 22:48:14 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "AddUserPermissionRel", namespace = "http://userpermissionrel.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddUserPermissionRel", namespace = "http://userpermissionrel.psr.com/")

public class AddUserPermissionRel {

    @XmlElement(name = "arg0")
    private java.util.ArrayList<com.psr.model.UserPermissionRel> arg0;

    public java.util.ArrayList<com.psr.model.UserPermissionRel> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.ArrayList<com.psr.model.UserPermissionRel> newArg0)  {
        this.arg0 = newArg0;
    }

}

