
package com.psr.record.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Wed Jan 30 21:54:27 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "AddResults", namespace = "http://record.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddResults", namespace = "http://record.psr.com/")

public class AddResults {

    @XmlElement(name = "arg0")
    private java.util.ArrayList<com.psr.model.RecordResult> arg0;

    public java.util.ArrayList<com.psr.model.RecordResult> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.ArrayList<com.psr.model.RecordResult> newArg0)  {
        this.arg0 = newArg0;
    }

}

