
package com.psr.permission.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Mon Jan 28 22:41:27 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "AddPermissions", namespace = "http://permission.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddPermissions", namespace = "http://permission.psr.com/")

public class AddPermissions {

    @XmlElement(name = "arg0")
    private java.util.ArrayList<com.psr.model.Permission> arg0;

    public java.util.ArrayList<com.psr.model.Permission> getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.ArrayList<com.psr.model.Permission> newArg0)  {
        this.arg0 = newArg0;
    }

}

