
package com.psr.permission.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Thu Jan 31 15:52:41 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "DeleteAllPermissionResponse", namespace = "http://permission.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeleteAllPermissionResponse", namespace = "http://permission.psr.com/")

public class DeleteAllPermissionResponse {


}

