
package com.psr.UploadFiles.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Fri Feb 22 15:43:45 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "InsertFileDBResponse", namespace = "http://UploadFiles.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsertFileDBResponse", namespace = "http://UploadFiles.psr.com/")

public class InsertFileDBResponse {


}

