
package com.psr.UploadFiles.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Thu Feb 21 13:49:28 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "UpLoad", namespace = "http://UploadFiles.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpLoad", namespace = "http://UploadFiles.psr.com/", propOrder = {"arg0", "arg1", "arg2"})

public class UpLoad {

    @XmlElement(name = "arg0")
    private byte[] arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;
    @XmlElement(name = "arg2")
    private java.lang.String arg2;

    public byte[] getArg0() {
        return this.arg0;
    }

    public void setArg0(byte[] newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

    public java.lang.String getArg2() {
        return this.arg2;
    }

    public void setArg2(java.lang.String newArg2)  {
        this.arg2 = newArg2;
    }

}

