
package com.psr.UploadFiles.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.2
 * Thu Feb 21 13:49:28 CST 2013
 * Generated source version: 2.7.2
 */

@XmlRootElement(name = "UpLoadResponse", namespace = "http://UploadFiles.psr.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpLoadResponse", namespace = "http://UploadFiles.psr.com/")

public class UpLoadResponse {


}

